apiVersion: v1
kind: Secret
metadata:
  name: multi-db-backup-secrets
  namespace: default
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "my-password-01"
  MONGO_ROOT_PASSWORD: "SecurePassword-01-02"
  CLICKHOUSE_PASSWORD: "secure-password-1-clk"
  RABBITMQ_PASSWORD: "secure-password-here"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
