apiVersion: batch/v1
kind: CronJob
metadata:
  name: all-db-backup
  namespace: default
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-worker
              image: registry-git.lsd.ufcg.edu.br/vtex-lab/mokirana/backup:latest
              env:
                - name: S3_BUCKET
                  value: "mokirana-backups"
                - name: S3_PREFIX
                  value: "full-infrastructure"
                - name: AWS_DEFAULT_REGION
                  value: "us-east-1"
                - name: MARIADB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: MARIADB_ROOT_PASSWORD
                - name: MONGO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: MONGO_ROOT_PASSWORD
                - name: CLICKHOUSE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: CLICKHOUSE_PASSWORD
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: RABBITMQ_PASSWORD
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_SESSION_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: multi-db-backup-secrets
                      key: AWS_SESSION_TOKEN
          volumes:
            - name: backup-storage
              ephemeral:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: "gp3-tagged"
                    resources:
                      requests:
                        storage: 1Ti
