---
name: Build restapi test image and run tests on it
run-name: Build restapi test image and run tests on it
permissions: read-all
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "rest_api/**"
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub (optional)
        env:
          username: ${{ secrets.EXT_DOCKER_LOGIN }}
          password: ${{ secrets.EXT_DOCKER_TOKEN }}
        if: ${{ env.username != '' && env.password != ''}}
        uses: docker/login-action@v3
        with:
          username: ${{ env.username }}
          password: ${{ env.password }}

      - name: Set up etcd service
        run: |
          if [ "$(docker ps -aq -f name=^/etcd$)" ]; then
            docker rm -f etcd
          fi
          docker run -d --name etcd -p 2379:2379 -p 2380:2380 \
            quay.io/coreos/etcd:v3.5.9 \
            etcd \
            --listen-peer-urls http://0.0.0.0:2380 \
            --listen-client-urls http://0.0.0.0:2379 \
            --advertise-client-urls http://127.0.0.1:2379 \
            --initial-cluster-token etcd-cluster-1 \
            --initial-advertise-peer-urls http://127.0.0.1:2380 \
            --initial-cluster default=http://127.0.0.1:2380

      - name: Verify etcd is running
        run: |
          curl -L http://127.0.0.1:2379/health

      - name: Build image
        run: bash -x build.sh rest_api build

      - name: Build test image and run tests
        env:
          ETCD_HOST: http://127.0.0.1:2379
        run: bash -x rest_api/run_test.sh

      - name: Stop and remove etcd container
        if: ${{ always() }}
        run: |
          if [ "$(docker ps -q -f name=^/etcd$)" ]; then
            docker stop etcd || true
          fi
          if [ "$(docker ps -aq -f name=^/etcd$)" ]; then
            docker rm etcd || true
          fi
